update deployment scripts & db save

diff --git a/deployment/dependencies b/deployment/dependencies
--- a/deployment/dependencies
+++ b/deployment/dependencies
@@ -28,21 +28,21 @@ ln -s ../../../uploads $HERE/public/uploads
 
 # Make sure node_modules exists so npm doesn't go searching
 # up the filesystem tree
-mkdir -p node_modules
+# mkdir -p node_modules
 
 # If there is no package.json file then we don't need npm install
-if [ -f './package.json' ]; then
+#if [ -f './package.json' ]; then
   # Install npm modules
   # Use a suitable version of Python
   # export PYTHON=/usr/bin/python26
-  npm install
-  if [ $? -ne 0 ]; then
-    echo "Error during npm install!"
-    exit 1
-  fi
-fi
+  #npm install
+  #if [ $? -ne 0 ]; then
+    #echo "Error during npm install!"
+    #exit 1
+  #fi
+#fi
 
-node app apostrophe-migrations:migrate --safe
+#node app apostrophe-migrations:migrate --safe
 # Generate new static asset files for this
 # deployment of the app without shutting down
-node app apostrophe:generation
+#node app apostrophe:generation
